---
framework: "jest"
blocklist:
  - "src/arith.test.js##2 + 3 = 5"
postMerge:
  pattern:
    - "./tests/*.test.ts"
preMerge:
  pattern:
    - "./tests/*.test.ts"
preRun:
  - npm install
postRun:
  - node --version
version: 2.0